### ISSUE TITLE
Add a readme.md file with setup/testing instructions

### ISSUE THREAD

**Issue by MickeyKay** [BraadMartin/genesis-rest-api-integration#1]
If you do this, I'd love to get in and play around a bit to see if there's maybe an automated way to loop through all genesis hooks.

**Comment by BraadMartin** [comment]
I just finished refactoring the method for firing the hooks into a single loop, and now it's much cleaner. Now we have an array of all the supported Genesis hooks we will fire, and of course the array is filterable so anyone can add or remove specific hooks.

I do still need to add some setup and testing instructions though. I'll try to get some screenshots included that show the normal response vs. the response with the plugin active and write up some usage examples.
